### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dojima** [norihiro/obs-async-audio-filter#3]
Firstly, thanks for this plugin.  I was pulling my hair out trying to solve this issue.  I do have a few questions though.

- Is there any reason why I might want to use OBS time instead of my device's clock?
- Is there any way to apply the filter to global audio devices or should I just be adding it to each audio input and output capture source?
- During my testing, I did notice one audio glitch, but it was when I still had a global audio device enabled—even though I didn't enable it as a track to be saved in the test recording.  Is it reasonable to assume that I should be disabling all global audio devices to ensure all audio is run through the filter?

Thanks again.

**Comment by norihiro** [comment]
> Is there any reason why I might want to use OBS time instead of my device's clock?

It's related to the implementation in libobs, the core of OBS.
If set to `OBS time` on the property, the audio source will send an OBS's timestamp which describes when the audio should be presented. This filter counts how many samples are passed and when the audio source started. Based on these numbers, this filter determines how many samples to be inserted or removed. If set to device's clock, the necessary timestamp is not passed to this filter.

> Is there any way to apply the filter to global audio devices

You can also apply audio filters to global audio devices such as Desktop Audio and Mic/Aux.
1. Open `Audio Mixer` (maybe already there by default.)
2. Right click your device or click 3-dot icon.
3. Choose `Filters` on the popup menu.

A global audio device is just a normal source like other audio sources but not associated to any scenes.

> Is it reasonable to assume that I should be disabling all global audio devices to ensure all audio is run through the filter?

The glitch will be observed if there is even one audio source running slow, even if it's muted by Audio Mixer. If you don't need the audio, I recommend to remove. You may also consider [obs-mute-filter](https://github.com/norihiro/obs-mute-filter/), which address the same issue.
