### ISSUE TITLE
Location of logfile

### ISSUE THREAD

**Issue by Fred-DTV** [norihiro/obs-async-audio-filter#5]
Sorry this might be a stupid question, but where are the log files saved?

I would like to take a look into the logs and see if it is working

**Comment by norihiro** [comment]
1. Click `Help` on the menu of OBS
2. Click `Log Files`
3. Click `Show Log Files` and you will find recent log files.
   You may click `View Current Log` instead.

Please search lines starting with `[obs-async-audio-filter]`.

**Comment by Fred-DTV** [comment]
ah of course it is just in the regular obs logs. thanks!
I knew it was a stupid question haha
