### ISSUE TITLE
Cannot use this with VLC Video Source?

### ISSUE THREAD

**Issue by duclepham** [norihiro/obs-async-audio-filter#9]
In the ReadMe section it says,
_Do not use this plugin for local file players such as Media Source and VLC Video Source._

What does this mean exactly?

I have VLC Video Source in my Sources, but in terms of Audio Inputs, I only have Desktop Audio and Mic. I plan to apply this filter on the Desktop Audio. Is this still OK?

Thanks!

**Comment by norihiro** [comment]
> I plan to apply this filter on the Desktop Audio. Is this still OK?

Yes, this is OK.
